name: nf-core-rrna-ampliseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.7 #newest version
  - multiqc=1.6 #newest version
  - cutadapt=1.18 #newest version
